import type { PhaseData } from "./lib/types";

export const phases: PhaseData[] = [
  {
    id: "extraction", slug: "extraction", sortOrder: 0,
    title: "Phase 1: Extraction",
    description: "Collect raw knowledge from Koray's resources, YouTube, GPTs, and client projects",
    tasks: [
      { id: "e1", phaseId: "extraction", title: "Scrape all website articles (~699)", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 0 },
      { id: "e2", phaseId: "extraction", title: "Extract YouTube transcripts (~53)", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 1 },
      { id: "e3", phaseId: "extraction", title: "Build custom scraper tool", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 2 },
      { id: "e4", phaseId: "extraction", title: "Extract Custom GPT prompts (47)", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 3 },
      { id: "e5", phaseId: "extraction", title: "Build Strategy Snapshot tool", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 4 },
      { id: "e6", phaseId: "extraction", title: "Run snapshots on Koray's 10 projects", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 5 },
      { id: "e7", phaseId: "extraction", title: "Receive 40-50+ Custom GPTs from Sardar", status: "blocked", assignedTo: "Sardar", blockedBy: "Sardar sending via WhatsApp", sortOrder: 6 },
      { id: "e8", phaseId: "extraction", title: "Receive Content Rules Google Doc", status: "blocked", assignedTo: "Sardar", blockedBy: "Sardar sending doc", sortOrder: 7 },
      { id: "e9", phaseId: "extraction", title: "Receive structure/layout examples doc", status: "blocked", assignedTo: "Sardar", blockedBy: "Sardar sending doc", sortOrder: 8 },
    ],
  },
  {
    id: "strategy-snapshots", slug: "strategy-snapshots", sortOrder: 1,
    title: "Phase 1.5: Strategy Snapshots",
    description: "Crawl project sites and extract structural blueprints",
    tasks: [
      { id: "ss1", phaseId: "strategy-snapshots", title: "Build Strategy Snapshot tool", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 0 },
      { id: "ss2", phaseId: "strategy-snapshots", title: "Get 10 project URLs from Sardar", status: "done", assignedTo: "Sardar", blockedBy: null, sortOrder: 1 },
      { id: "ss3", phaseId: "strategy-snapshots", title: "Run snapshots on all 10 projects", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 2 },
      { id: "ss4", phaseId: "strategy-snapshots", title: "Review blueprints for completeness", status: "pending", assignedTo: "Michael", blockedBy: null, sortOrder: 3 },
    ],
  },
  {
    id: "consolidation", slug: "consolidation", sortOrder: 2,
    title: "Phase 2: Knowledge Consolidation",
    description: "Organize 749 source files into 17-topic knowledge base (965 files)",
    tasks: [
      { id: "c1", phaseId: "consolidation", title: "Define topic taxonomy (17 categories)", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 0 },
      { id: "c2", phaseId: "consolidation", title: "Create consolidated-knowledge/ folder structure", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 1 },
      { id: "c3", phaseId: "consolidation", title: "Route all 749 files to topic folders", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 2 },
      { id: "c4", phaseId: "consolidation", title: "Fix sparse folders with content-level search", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 3 },
      { id: "c5", phaseId: "consolidation", title: "Create INDEX.md master catalog", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 4 },
      { id: "c6", phaseId: "consolidation", title: "Validate coverage (749 → 965 routed copies)", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 5 },
    ],
  },
  {
    id: "chunking", slug: "chunking", sortOrder: 3,
    title: "Phase 2.5: Chunking Pipeline",
    description: "Split consolidated files into 200-1000 token retrievable units with metadata",
    tasks: [
      { id: "ch1", phaseId: "chunking", title: "Design chunking strategy per content type", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 0 },
      { id: "ch2", phaseId: "chunking", title: "Build chunking pipeline script", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 1 },
      { id: "ch3", phaseId: "chunking", title: "Define metadata schema", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 2 },
      { id: "ch4", phaseId: "chunking", title: "Process website articles into chunks", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 3 },
      { id: "ch5", phaseId: "chunking", title: "Process video transcripts into chunks", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 4 },
      { id: "ch6", phaseId: "chunking", title: "Process GPT prompts + strategy blueprints", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 5 },
      { id: "ch7", phaseId: "chunking", title: "Deduplicate chunks across categories", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 6 },
      { id: "ch8", phaseId: "chunking", title: "Validate chunk quality (spot-check 10%)", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 7 },
    ],
  },
  {
    id: "database", slug: "database", sortOrder: 4,
    title: "Phase 3: Vector Database & RAG",
    description: "Store embeddings, build retrieval pipeline for agent knowledge",
    tasks: [
      { id: "d1", phaseId: "database", title: "Choose vector DB", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 0 },
      { id: "d2", phaseId: "database", title: "Set up database with categorized collections", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 1 },
      { id: "d3", phaseId: "database", title: "Generate embeddings for all chunks", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 2 },
      { id: "d4", phaseId: "database", title: "Build retrieval function", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 3 },
      { id: "d5", phaseId: "database", title: "Build multi-stage generation pipeline", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 4 },
      { id: "d6", phaseId: "database", title: "Test retrieval accuracy", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 5 },
      { id: "d7", phaseId: "database", title: "Deploy with shared access", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 6 },
    ],
  },
  {
    id: "dashboard", slug: "dashboard", sortOrder: 5,
    title: "Phase 4: Dashboard & Auth",
    description: "Web interface for tracking progress and interacting with agents",
    tasks: [
      { id: "ui1", phaseId: "dashboard", title: "Deploy progress tracker to Railway", status: "done", assignedTo: "Michael", blockedBy: null, sortOrder: 0 },
      { id: "ui2", phaseId: "dashboard", title: "Add dashboard editing (CRUD)", status: "in-progress", assignedTo: "Michael", blockedBy: null, sortOrder: 1 },
      { id: "ui3", phaseId: "dashboard", title: "Knowledge browser UI", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 2 },
      { id: "ui4", phaseId: "dashboard", title: "Agent interaction interface", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 3 },
      { id: "ui5", phaseId: "dashboard", title: "Auth (Michael + Sardar logins)", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 4 },
      { id: "ui6", phaseId: "dashboard", title: "Generation history + export", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 5 },
    ],
  },
  {
    id: "content-tool", slug: "content-tool", sortOrder: 6,
    title: "Phase 5: Content Writing Tool",
    description: "AI content writer trained on Koray's proven projects and knowledge",
    tasks: [
      { id: "ct1", phaseId: "content-tool", title: "Define content types (service, blog, location page)", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 0 },
      { id: "ct2", phaseId: "content-tool", title: "Build brief generation stage", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 1 },
      { id: "ct3", phaseId: "content-tool", title: "Build content generation stage", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 2 },
      { id: "ct4", phaseId: "content-tool", title: "Build self-check/validation stage", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 3 },
      { id: "ct5", phaseId: "content-tool", title: "Train on Koray's 60-70 projects", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 4 },
      { id: "ct6", phaseId: "content-tool", title: "Test and iterate on output quality", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 5 },
    ],
  },
  {
    id: "gmb-tool", slug: "gmb-tool", sortOrder: 7,
    title: "Phase 6: GMB Optimization Tool",
    description: "Local SEO tool with SOP-based task execution",
    tasks: [
      { id: "gm1", phaseId: "gmb-tool", title: "Define 10-15 standardized GMB tasks from SOPs", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 0 },
      { id: "gm2", phaseId: "gmb-tool", title: "Build task execution system", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 1 },
      { id: "gm3", phaseId: "gmb-tool", title: "Integrate with existing audit tool", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 2 },
      { id: "gm4", phaseId: "gmb-tool", title: "Add local outreach layer", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 3 },
      { id: "gm5", phaseId: "gmb-tool", title: "Get 20-30 local business projects for training", status: "pending", assignedTo: "Sardar", blockedBy: null, sortOrder: 4 },
      { id: "gm6", phaseId: "gmb-tool", title: "Test with real client end-to-end", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 5 },
    ],
  },
  {
    id: "scaling", slug: "scaling", sortOrder: 8,
    title: "Phase 7: Scaling & Iteration",
    description: "Ongoing improvement, new knowledge sources, additional tools",
    tasks: [
      { id: "sc1", phaseId: "scaling", title: "Add new client projects as case studies", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 0 },
      { id: "sc2", phaseId: "scaling", title: "Build additional specialized tools", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 1 },
      { id: "sc3", phaseId: "scaling", title: "Benchmark outputs vs competitors", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 2 },
      { id: "sc4", phaseId: "scaling", title: "Scale to team use (role-based access)", status: "pending", assignedTo: null, blockedBy: null, sortOrder: 3 },
    ],
  },
];
