/* Mock data — fixture for the redesign so pages look real */

const SAMPLE_BRIEF = {
  id: 'br_8a1f9',
  topic: 'Best ERP software for manufacturing in 2026',
  pageType: 'comparison',
  niche: 'B2B SaaS',
  location: null,
  clientName: 'Vector Industries',
  status: 'reviewing',
  version: 4,
  qualityScore: 87,
  updatedAt: '2 hours ago',
  data: {
    titleTag: {
      titleTag: 'Best ERP Software for Manufacturing (2026): 11 Tools Compared',
      contextualAttributes: ['comparison', 'recency-marker', 'numeric-hook'],
      rationale: 'Comparison + year qualifier + count satisfies SERP intent for buyer queries.',
    },
    contextualVectors: [
      'manufacturing-vertical', 'discrete-vs-process', 'cloud-erp',
      'mid-market', 'on-prem-migration', 'implementation-cost', 'integration-erp',
    ],
    knowledgeGaps: [
      'No coverage of MES integration',
      'No carbon-tracking module comparison',
      'Lacks 2026 pricing data for SAP S/4HANA',
    ],
    headings: [
      { level: 1, text: 'Best ERP Software for Manufacturing in 2026',
        contentDesignPattern: 'paragraph', ruleCodes: ['FS', 'TF-IDF', 'NER'],
        targetQueries: [{ query: 'best erp for manufacturing', volume: 8100, intent: 'commercial' }],
        wordCountTarget: 220, snippetTarget: true, paaTarget: false,
        serpFeatures: ['FS', 'PAA'], intent: 'commercial',
        structureInstructions: 'Open with a definitive recommendation matrix. Lead with 2026 framing and a 50-word featured-snippet target. Cite analyst sources within the first 200 words.' },
      { level: 2, text: 'What ERP software does best for manufacturing',
        contentDesignPattern: 'paragraph', ruleCodes: ['TF-IDF', 'NER'],
        targetQueries: [
          { query: 'what is manufacturing erp', volume: 2900, intent: 'informational' },
          { query: 'erp manufacturing definition', volume: 880, intent: 'informational' },
        ],
        wordCountTarget: 140, intent: 'informational', serpFeatures: ['FS'],
        structureInstructions: '2-paragraph definitional answer. Bind to MES, MRP, and shop-floor terms. Mention Tier-1/2/3 vendor classifications.' },
      { level: 3, text: 'Discrete vs process manufacturing ERP',
        contentDesignPattern: 'comparison', ruleCodes: ['PAA'],
        targetQueries: [{ query: 'discrete vs process manufacturing erp', volume: 1300, intent: 'comparative' }],
        wordCountTarget: 110, paaTarget: true, intent: 'comparative',
        serpFeatures: ['PAA'],
        structureInstructions: 'Two-column comparison. Bullets only, no narrative. Anchor each side with one named vendor.' },
      { level: 2, text: 'Top 11 ERP platforms ranked',
        contentDesignPattern: 'table', ruleCodes: ['FS', 'TF-IDF', 'NER', 'SERP'],
        targetQueries: [
          { query: 'best erp software manufacturing 2026', volume: 5400, intent: 'commercial' },
          { query: 'top manufacturing erp', volume: 2400, intent: 'commercial' },
        ],
        wordCountTarget: 80, snippetTarget: true, intent: 'commercial', serpFeatures: ['FS'],
        structureInstructions: '8-column comparison table. Columns: Vendor, Best for, Deployment, Pricing tier, Trial, Mfg modules, G2 score, Verdict.' },
      { level: 3, text: 'SAP S/4HANA Cloud',
        contentDesignPattern: 'paragraph', ruleCodes: ['NER', 'EAT'],
        targetQueries: [{ query: 'sap s/4hana manufacturing review', volume: 720, intent: 'investigational' }],
        wordCountTarget: 180, intent: 'investigational', serpFeatures: [],
        structureInstructions: 'Vendor card. Lead with verdict (2 sentences). Bullets for strengths/limitations/pricing/best-for.' },
      { level: 3, text: 'Microsoft Dynamics 365 Supply Chain',
        contentDesignPattern: 'paragraph', ruleCodes: ['NER', 'EAT'],
        targetQueries: [{ query: 'dynamics 365 manufacturing erp', volume: 590, intent: 'investigational' }],
        wordCountTarget: 180, intent: 'investigational', serpFeatures: [],
        structureInstructions: 'Vendor card matching previous pattern. Include Power Platform extensibility.' },
      { level: 3, text: 'NetSuite for manufacturing',
        contentDesignPattern: 'paragraph', ruleCodes: ['NER'],
        targetQueries: [{ query: 'netsuite manufacturing erp', volume: 480, intent: 'investigational' }],
        wordCountTarget: 170, intent: 'investigational', serpFeatures: [],
        structureInstructions: 'Vendor card. Emphasize mid-market positioning.' },
      { level: 2, text: 'How to choose: a 7-step decision framework',
        contentDesignPattern: 'list', ruleCodes: ['FS', 'PAA'],
        targetQueries: [
          { query: 'how to choose erp for manufacturing', volume: 1900, intent: 'informational' },
          { query: 'erp selection criteria', volume: 720, intent: 'informational' },
        ],
        wordCountTarget: 320, paaTarget: true, intent: 'informational', serpFeatures: ['PAA', 'FS'],
        structureInstructions: 'Numbered list with 7 steps. Each step gets a 35-50 word explanation. Bold the step verb.' },
      { level: 2, text: 'Pricing & total cost of ownership',
        contentDesignPattern: 'table', ruleCodes: ['TF-IDF', 'NER'],
        targetQueries: [
          { query: 'manufacturing erp cost', volume: 1600, intent: 'commercial' },
          { query: 'erp implementation cost', volume: 880, intent: 'commercial' },
        ],
        wordCountTarget: 240, intent: 'commercial', serpFeatures: ['FS'],
        structureInstructions: 'Pricing comparison table + TCO narrative. Include implementation, license, training, hardware as separate rows.' },
      { level: 2, text: 'Frequently asked questions',
        contentDesignPattern: 'list', ruleCodes: ['PAA', 'FAQ-schema'],
        targetQueries: [{ query: 'erp manufacturing questions', volume: 320, intent: 'informational' }],
        wordCountTarget: 380, paaTarget: true, intent: 'informational', serpFeatures: ['PAA'],
        structureInstructions: '8 questions sourced directly from PAA. Each answer 40-60 words. Use FAQ schema markup.' },
    ],
    entityMap: [
      { entity: 'SAP S/4HANA', type: 'product', relevance: 'primary' },
      { entity: 'Microsoft Dynamics 365', type: 'product', relevance: 'primary' },
      { entity: 'Oracle NetSuite', type: 'product', relevance: 'primary' },
      { entity: 'Epicor Kinetic', type: 'product', relevance: 'primary' },
      { entity: 'Infor CloudSuite', type: 'product', relevance: 'secondary' },
      { entity: 'IFS Cloud', type: 'product', relevance: 'secondary' },
      { entity: 'Plex Systems', type: 'product', relevance: 'secondary' },
      { entity: 'Discrete manufacturing', type: 'concept', relevance: 'primary' },
      { entity: 'Process manufacturing', type: 'concept', relevance: 'primary' },
      { entity: 'MRP', type: 'concept', relevance: 'secondary' },
      { entity: 'MES', type: 'concept', relevance: 'secondary' },
      { entity: 'BOM (Bill of Materials)', type: 'concept', relevance: 'secondary' },
      { entity: 'Gartner', type: 'org', relevance: 'contextual' },
      { entity: 'Forrester Wave', type: 'org', relevance: 'contextual' },
      { entity: 'ISO 9001', type: 'standard', relevance: 'contextual' },
      { entity: 'Industry 4.0', type: 'concept', relevance: 'contextual' },
    ],
    connectionMap: [
      { fromHeading: 'Top 11 ERP platforms ranked', toPage: '/blog/sap-s4hana-vs-netsuite', anchorText: 'SAP vs NetSuite deep-dive', reason: 'Reinforces topical cluster on enterprise ERP comparisons.' },
      { fromHeading: 'How to choose: a 7-step decision framework', toPage: '/guides/erp-rfp-template', anchorText: 'Download our ERP RFP template', reason: 'Conversion bridge to gated asset.' },
      { fromHeading: 'Pricing & total cost of ownership', toPage: '/calculators/erp-tco', anchorText: 'Estimate your TCO', reason: 'Interactive tool drives bottom-of-funnel engagement.' },
      { fromHeading: 'Discrete vs process manufacturing ERP', toPage: '/glossary/discrete-manufacturing', anchorText: 'discrete manufacturing', reason: 'Glossary support for entity-based query.' },
    ],
    competitors: [
      { url: 'gartner.com/peer-insights/manufacturing-erp', title: 'Manufacturing ERP — Gartner Peer Insights', headings: ['Overview', 'Top Picks 2025', 'SAP S/4HANA Review', 'Dynamics 365 Review', 'NetSuite Review', 'IFS Review', 'How to choose', 'FAQ'], wordCount: 3800, serpPosition: 1 },
      { url: 'g2.com/categories/erp-systems/manufacturing', title: 'Best Manufacturing ERP Software 2025 | G2', headings: ['Top-Rated Software', 'User Reviews', 'Buyer Guide', 'Filters'], wordCount: 2100, serpPosition: 2 },
      { url: 'softwareadvice.com/manufacturing-erp/', title: 'Top Manufacturing ERP Software 2025 - Software Advice', headings: ['Best ERP for Manufacturers', 'Comparison Chart', 'Pricing Guide', 'Buyer\'s Guide'], wordCount: 4200, serpPosition: 3 },
      { url: 'capterra.com/manufacturing-erp-software/', title: 'Best Manufacturing ERP Software | Capterra', headings: ['Sort by', 'Top Reviews', 'Free Trial Options'], wordCount: 1600, serpPosition: 4 },
    ],
    queryPreAnalysis: {
      searchIntent: 'commercial',
      queryType: 'mid-tail',
      queryCompleteness: { isComplete: false, missingQualifiers: ['company size', 'industry sub-vertical', 'deployment preference'] },
      audienceSegments: { primary: 'Manufacturing operations leaders', secondary: 'IT decision makers', tertiary: 'Consultants & implementors' },
      businessModel: 'lead-gen',
      intentSatisfactionThreshold: { depth: 'deep', description: 'Requires 3000+ words, vendor cards, pricing data, and a decision framework.' },
      freshnessRequirement: 'time-sensitive',
    },
    serpAnalysis: {
      consensusCoverage: ['vendor rankings', 'pricing ranges', 'deployment options', 'best-for verdicts', 'reviewer ratings'],
      serpGaps: ['2026 pricing updates', 'AI/copilot capabilities', 'sustainability/carbon modules'],
      compressionPatterns: ['generic "what is ERP" intros', 'unsourced "fastest ROI" claims', 'feature lists without context'],
      featuredSnippetOpportunities: [
        { query: 'best erp for manufacturing', currentFormat: 'paragraph (Gartner)', strategy: 'Win with 50-word paragraph + vendor count.' },
        { query: 'discrete vs process manufacturing', currentFormat: 'table (Investopedia)', strategy: 'Match table format, lead with a one-line distinction.' },
        { query: 'how to choose erp', currentFormat: 'list (G2)', strategy: 'Provide a 7-step numbered framework.' },
      ],
      aiOverviewPresence: true,
      serpFeaturePresence: { imagePack: false, video: true, maps: false, forums: true, paa: true, knowledgePanel: false },
      autocompleteVariations: ['best erp for small manufacturers', 'best erp for food manufacturing', 'best erp 2026', 'cloud erp manufacturing'],
    },
    deepCompetitorAnalysis: {
      competitors: [
        { url: 'gartner.com/peer-insights/manufacturing-erp', title: 'Gartner Peer Insights', serpPosition: 1,
          headingDepth: { h1: 1, h2: 8, h3: 14, h4: 2, maxDepth: 4 },
          contentDesignPatterns: ['table', 'vendor-cards', 'narrative'],
          strengths: ['Trusted analyst brand', 'Strong vendor coverage', 'Recent updates'],
          weaknesses: ['Behind email gate', 'No pricing depth', 'Weak FAQ'],
          topicalArchitecture: ['Top picks', 'Vendor reviews', 'How to choose'],
          entityCoverage: ['Gartner', 'SAP', 'Oracle', 'Microsoft', 'Epicor', 'Infor'],
        },
      ],
      crossCompetitorEntities: ['SAP S/4HANA', 'Microsoft Dynamics 365', 'NetSuite', 'Epicor Kinetic', 'Infor CloudSuite', 'IFS Cloud'],
      gapKeywords: ['ERP for medical device manufacturing', 'cloud ERP carbon tracking', 'AI copilot for ERP', 'cost to migrate from QuickBooks to ERP', 'manufacturing ERP for under 50 employees'],
    },
    topicalMap: [
      { topic: 'Best ERP software for manufacturing', relationship: 'root', clusterLabel: 'Pillar' },
      { topic: 'SAP S/4HANA review', relationship: 'supporting', suggestedPageType: 'review' },
      { topic: 'Microsoft Dynamics 365 review', relationship: 'supporting', suggestedPageType: 'review' },
      { topic: 'NetSuite manufacturing review', relationship: 'supporting', suggestedPageType: 'review' },
      { topic: 'Epicor Kinetic review', relationship: 'supporting', suggestedPageType: 'review' },
      { topic: 'ERP implementation cost', relationship: 'supporting', suggestedPageType: 'guide' },
      { topic: 'ERP for small manufacturers', relationship: 'adjacent', suggestedPageType: 'comparison' },
      { topic: 'Cloud vs on-prem ERP', relationship: 'adjacent', suggestedPageType: 'comparison' },
      { topic: 'Manufacturing MES vs ERP', relationship: 'adjacent', suggestedPageType: 'guide' },
      { topic: 'ERP RFP template', relationship: 'downstream', suggestedPageType: 'lead-magnet' },
      { topic: 'ERP TCO calculator', relationship: 'downstream', suggestedPageType: 'tool' },
      { topic: 'ERP demo checklist', relationship: 'downstream', suggestedPageType: 'lead-magnet' },
    ],
    headingValidation: {
      score: 8.6,
      issues: [
        { headingIndex: 4, headingText: 'SAP S/4HANA Cloud', issueType: 'continuity-break', severity: 'low',
          description: 'Vendor reviews break out of the comparison framing without a transition sentence.',
          suggestedFix: 'Add a 1-sentence connector before vendor H3s.' },
        { headingIndex: 8, headingText: 'Pricing & total cost of ownership', issueType: 'edge-case-missing', severity: 'medium',
          description: 'Missing self-hosted vs SaaS pricing distinction.',
          suggestedFix: 'Add an H3 splitting cloud and on-prem TCO.' },
      ],
    },
    qualityReport: {
      overallScore: 87,
      breakdown: {
        competitorCoverage: 91,
        intentSatisfaction: 88,
        semanticCoherence: 82,
        entityCompleteness: 84,
        headingQuality: 86,
      },
      knowledgeGaps: [
        'No coverage of MES integration',
        'No carbon-tracking module comparison',
        'Lacks 2026 pricing data for SAP S/4HANA',
      ],
      recommendations: [
        'Add an H3 for MES integration under "Top 11 ERP platforms ranked".',
        'Source 2026 SAP S/4HANA pricing from analyst notes before publishing.',
        'Add a sustainability module sub-section to lead in the SERP gap.',
      ],
    },
  },
};

const BRIEFS_LIST = [
  { id: 'br_8a1f9', topic: 'Best ERP software for manufacturing in 2026', niche: 'B2B SaaS', pageType: 'comparison', status: 'reviewing', version: 4, quality: 87, volume: 23400, updated: '2h ago' },
  { id: 'br_72b03', topic: 'How to migrate from QuickBooks to NetSuite', niche: 'B2B SaaS', pageType: 'guide', status: 'approved', version: 2, quality: 92, volume: 4800, updated: '1d ago', hasWriter: true },
  { id: 'br_61d44', topic: 'Top-rated CRM for small ecommerce stores', niche: 'B2B SaaS', pageType: 'comparison', status: 'draft', version: 1, quality: 62, volume: 12600, updated: '3d ago' },
  { id: 'br_5fc01', topic: 'AI content moderation tools compared (2026)', niche: 'AI tooling', pageType: 'comparison', status: 'reviewing', version: 3, quality: 79, volume: 9800, updated: '4d ago' },
  { id: 'br_4a210', topic: 'What is GEO (generative engine optimization)?', niche: 'SEO', pageType: 'guide', status: 'approved', version: 5, quality: 94, volume: 18900, updated: '6d ago', hasWriter: true },
  { id: 'br_3aa90', topic: 'Local SEO for HVAC companies in Phoenix', niche: 'Local SEO', pageType: 'location', status: 'draft', version: 1, quality: 54, volume: 2400, updated: '1w ago' },
  { id: 'br_2e189', topic: 'PIM vs DAM vs MDM: which one do you need?', niche: 'B2B SaaS', pageType: 'comparison', status: 'reviewing', version: 2, quality: 81, volume: 3200, updated: '1w ago' },
  { id: 'br_1f7c2', topic: 'Schema markup for SaaS landing pages', niche: 'Technical SEO', pageType: 'guide', status: 'approved', version: 4, quality: 89, volume: 5400, updated: '2w ago', hasWriter: true },
];

const PHASES = [
  { id: 'p1', title: 'Discovery', description: 'Keyword research & intent mapping', tasks: [
    { id: 't1', title: 'Keyword universe export (Ahrefs)', status: 'done' },
    { id: 't2', title: 'SERP feature audit', status: 'done' },
    { id: 't3', title: 'Competitor seed list', status: 'done' },
  ]},
  { id: 'p2', title: 'Briefing', description: 'AI-generated content briefs', tasks: [
    { id: 't4', title: 'Generate Q1 pillar briefs (8)', status: 'done' },
    { id: 't5', title: 'Brief review & approval', status: 'in-progress' },
    { id: 't6', title: 'Add 2026 pricing data', status: 'in-progress' },
    { id: 't7', title: 'MES integration coverage', status: 'blocked' },
  ]},
  { id: 'p3', title: 'Writing', description: 'Section-by-section generation', tasks: [
    { id: 't8', title: 'Draft Q1 pillar #1', status: 'in-progress' },
    { id: 't9', title: 'Vendor card template', status: 'pending' },
    { id: 't10', title: 'FAQ generation', status: 'pending' },
  ]},
  { id: 'p4', title: 'Publishing', description: 'QA, schema, deploy', tasks: [
    { id: 't11', title: 'FAQ schema markup', status: 'pending' },
    { id: 't12', title: 'Final pass review', status: 'pending' },
    { id: 't13', title: 'Vector industries handoff', status: 'pending' },
  ]},
];

const KNOWLEDGE_RESULTS = [
  { id: 'k1', title: 'Topical map prioritization framework', category: '02-topical-authority', sourceType: 'pdf', contentType: 'framework', tokenCount: 1820, score: 0.948, content: "When building topical authority, structure your content into root, supporting, adjacent, and downstream layers. Root topics anchor the topical map and answer the primary commercial intent. Supporting topics deepen entity coverage. Adjacent topics expand horizontally to related intents…" },
  { id: 'k2', title: 'Featured-snippet capture strategies', category: '05-on-page-seo', sourceType: 'video-transcript', contentType: 'tactic', tokenCount: 1240, score: 0.913, content: "To capture a paragraph snippet, place a 40-60 word answer directly under the H2 question. Lead with the entity definition, then bind to two supporting entities within the same paragraph. Avoid hedging language…" },
  { id: 'k3', title: 'Competitor heading depth analysis', category: '03-content-strategy', sourceType: 'article', contentType: 'analysis', tokenCount: 980, score: 0.872, content: "Measure heading depth by counting H1/H2/H3/H4 ratios across the top 10 SERP results. The median for commercial queries is H1:1, H2:6–9, H3:8–14, H4:0–2. Outliers under H3:4 are typically pages with weak topical depth…" },
  { id: 'k4', title: 'PAA harvesting via SerpAPI', category: '04-technical-seo', sourceType: 'pdf', contentType: 'tactic', tokenCount: 1430, score: 0.831, content: "People-Also-Ask boxes refresh based on click depth. Use SerpAPI's people_also_ask field with an expanded scrape after 2 levels. Cluster questions by intent type before mapping to brief headings…" },
  { id: 'k5', title: 'Schema markup for comparison pages', category: '15-schema-and-structured-data', sourceType: 'documentation', contentType: 'reference', tokenCount: 760, score: 0.794, content: "Use Product schema for each compared vendor, nested within an ItemList. Add aggregateRating only if first-party reviews exist. For FAQ blocks, FAQPage schema can co-exist on the same URL…" },
];

const CHAT_HISTORY = [
  { role: 'user', content: 'For a comparison page like "best ERP for manufacturing", what\'s the ideal heading depth?' },
  { role: 'assistant', content: 'For a commercial comparison query, the median top-10 distribution is H1:1, H2:6–9, H3:8–14, H4:0–2. Your current draft (H1:1, H2:5, H3:3) is shallow on H2/H3 — you\'re under-covering the SERP. Consider:\n\n• Adding 2–3 more H2s for missing dimensions (Pricing & TCO, Decision framework, FAQ).\n• Expanding H3s under each vendor (verdict, pricing, integrations, best-for).\n• Keep H4s reserved for sub-features within a vendor card.\n\nThe Gartner page at position 1 uses H2:8, H3:14. That\'s your target ceiling.', sources: [
    { id: 'k1', title: 'Topical map prioritization framework' },
    { id: 'k3', title: 'Competitor heading depth analysis' },
  ]},
  { role: 'user', content: 'What featured snippets should I target?' },
];

const HISTORY_ITEMS = [
  { id: 'g1', kind: 'brief', topic: 'Best ERP software for manufacturing in 2026', agent: 'brief-v2', tokens: 12450, at: 'Today, 14:22' },
  { id: 'g2', kind: 'section', topic: 'SAP S/4HANA Cloud — vendor card', agent: 'section-writer', tokens: 1820, at: 'Today, 13:55' },
  { id: 'g3', kind: 'chat', topic: 'Heading depth for comparison pages', agent: 'chat-rag', tokens: 6300, at: 'Today, 11:08' },
  { id: 'g4', kind: 'brief', topic: 'How to migrate from QuickBooks to NetSuite', agent: 'brief-v2', tokens: 11860, at: 'Yesterday, 17:40' },
  { id: 'g5', kind: 'section', topic: 'FAQ block — generative engine optimization', agent: 'section-writer', tokens: 2100, at: 'Yesterday, 16:11' },
  { id: 'g6', kind: 'chat', topic: 'PAA harvesting via SerpAPI', agent: 'chat-rag', tokens: 4200, at: '2 days ago' },
  { id: 'g7', kind: 'brief', topic: 'AI content moderation tools compared', agent: 'brief-v2', tokens: 13100, at: '3 days ago' },
];

Object.assign(window, { SAMPLE_BRIEF, BRIEFS_LIST, PHASES, KNOWLEDGE_RESULTS, CHAT_HISTORY, HISTORY_ITEMS });
